<?php

define("SIGN_UP_USE_CASE_NO_ERRORS", 0);
define("SIGN_UP_USE_CASE_ERROR_EMPTY_EMAIL", 1);
define("SIGN_UP_USE_CASE_ERROR_INVALID_EMAIL_FORMAT", 2);
define("SIGN_UP_USE_CASE_ERROR_BLACKLISTED_EMAIL", 4);
define("SIGN_UP_USE_CASE_ERROR_PASSWORD_MISMATCH", 8);
define("SIGN_UP_USE_CASE_ERROR_INVALID_PASSWORD", 16);
define("SIGN_UP_USE_CASE_ERROR_INVALID_PASSWORD_REPEAT", 32);
define("SIGN_UP_USE_CASE_ERROR_USER_EXISTS", 64);
define("SIGN_UP_USE_CASE_STORAGE_ERROR", 128);